
package com.heq.schema.beans;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "com.heq.webservice.service.UserService", targetNamespace = "http://www.springframework.org/schema/beans", wsdlLocation = "http://localhost:8080/ws/webService?wsdl")
public class ComHeqWebserviceServiceUserService
    extends Service
{

    private final static URL COMHEQWEBSERVICESERVICEUSERSERVICE_WSDL_LOCATION;
    private final static WebServiceException COMHEQWEBSERVICESERVICEUSERSERVICE_EXCEPTION;
    private final static QName COMHEQWEBSERVICESERVICEUSERSERVICE_QNAME = new QName("http://www.springframework.org/schema/beans", "com.heq.webservice.service.UserService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/webService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COMHEQWEBSERVICESERVICEUSERSERVICE_WSDL_LOCATION = url;
        COMHEQWEBSERVICESERVICEUSERSERVICE_EXCEPTION = e;
    }

    public ComHeqWebserviceServiceUserService() {
        super(__getWsdlLocation(), COMHEQWEBSERVICESERVICEUSERSERVICE_QNAME);
    }

    public ComHeqWebserviceServiceUserService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMHEQWEBSERVICESERVICEUSERSERVICE_QNAME, features);
    }

    public ComHeqWebserviceServiceUserService(URL wsdlLocation) {
        super(wsdlLocation, COMHEQWEBSERVICESERVICEUSERSERVICE_QNAME);
    }

    public ComHeqWebserviceServiceUserService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMHEQWEBSERVICESERVICEUSERSERVICE_QNAME, features);
    }

    public ComHeqWebserviceServiceUserService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ComHeqWebserviceServiceUserService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UserService
     */
    @WebEndpoint(name = "UserServiceImplPort")
    public UserService getUserServiceImplPort() {
        return super.getPort(new QName("http://www.springframework.org/schema/beans", "UserServiceImplPort"), UserService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserService
     */
    @WebEndpoint(name = "UserServiceImplPort")
    public UserService getUserServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.springframework.org/schema/beans", "UserServiceImplPort"), UserService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COMHEQWEBSERVICESERVICEUSERSERVICE_EXCEPTION!= null) {
            throw COMHEQWEBSERVICESERVICEUSERSERVICE_EXCEPTION;
        }
        return COMHEQWEBSERVICESERVICEUSERSERVICE_WSDL_LOCATION;
    }

}
